services:
  - type: worker
    name: husker
    env: python
    repo: https://github.com/MustaphaMLawal-herlystack/husker/
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"

